server:
  port: 8050
spring:
  application:
    name: industryzuul
  security:
    user:
      name: vbooster
      password: 123456a
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 100MB #设置单个文件最大长度
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8030/eureka/
zuul:
  sensitive-headers: '*'
  routes:
    storagemanage: /sm/**
    outboundmanage: /om/**
    basicmanage: /ba/**
    authoritymanage: /am/**
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
logging:
  config: classpath:logback-spring-test.xml