server:
  port: 8034
spring:
  profiles:
    include: common
  application:
    name: authoritymanage
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    com:
      smartindustry:
        common:
          mapper: debug
  config: classpath:logback-spring-test.xml
