server:
  port: 8031
spring:
  profiles:
    include: common
  application:
    name: storagemanage
logging:
  level:
    com:
      smartindustry:
        common:
          mapper: debug
  config: classpath:logback-spring-test.xml

schedule:
  storage:
    trigger:  0 30 07,19 * * ?
