server:
  port: 8037
spring:
  profiles:
    include: common
  application:
    name: bigdatamanage
logging:
  level:
    com:
      smartindustry:
        bigdata:
          mapper: debug
  config: classpath:logback-spring-test.xml
