server:
  port: 8030
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8030/eureka/
logging:
  config: classpath:logback-spring-test.xml

spring:
  security:
    user:
      name: vbooster
      password: vbooster@123